# Generated by Django 3.2.7 on 2021-09-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dep', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=500)),
            ],
        ),
    ]
